title: Projects
description: My Personal Website
author: Tulin Akdogan
github: https://github.com/tulinn
about: I am management engineering student at University of Waterloo. 
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/tulinn
    - text: XML Feed
      url: /feed.xml
url: "https://tulinakdogan.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown